batch_size: 256
dataset:
  action_scale_path: exps/bc_isaac/shard4/action_scale.pt
  max_episodes: -1
  max_len: -1
  normalize_actions: true
  path: /home/pvelmuru/projects/shard5
  use_default_socket_pad: true
epoch_len: 1000
eval_with_env: 0
grad_clip: 5.0
graphics_device_id: -1
headless: true
init_checkpoint: exps/bc_isaac/shard4/model0.pt
isaacgym_envs_path: ../manifeel-isaacgymenvs-tacsl-manifeel-rl
lr: 0.0001
num_epoch: 100
num_eval_envs: 16
num_eval_episodes: 20
policy:
  dropout: 0.5
  hidden_dim: 256
  layer_norm: 0
  num_layer: 3
rl_device: cuda:0
save_dir: exps/bc_isaac/shard5
save_per: -1
seed: 1
sim_device: cuda:0
use_wb: 0
weight_decay: 0.0
